//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int id { get; set; }
        public Nullable<int> nodeID1 { get; set; }
        public Nullable<int> nodeID2 { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> distance { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> paperID { get; set; }
    
        public virtual node node { get; set; }
        public virtual node node1 { get; set; }
        public virtual paper paper { get; set; }
    }
}
