//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public node()
        {
            this.link = new HashSet<link>();
            this.link1 = new HashSet<link>();
        }
    
        public int id { get; set; }
        public string value { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<int> weight { get; set; }
    
        public virtual ICollection<link> link { get; set; }
        public virtual ICollection<link> link1 { get; set; }
    }
}
