//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        public paper()
        {
            this.link1 = new HashSet<link>();
        }
    
        public int ID { get; set; }
        public string Authors { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public string SourceTitle { get; set; }
        public string Volume { get; set; }
        public string Issue { get; set; }
        public string ArtNo { get; set; }
        public Nullable<int> PageStart { get; set; }
        public Nullable<int> PageEnd { get; set; }
        public string PageCount { get; set; }
        public Nullable<int> CitedBy { get; set; }
        public string Link { get; set; }
        public string Affiliations { get; set; }
        public string AuthorsWithAffiliations { get; set; }
        public string Abstract { get; set; }
        public string AuthorKeywords { get; set; }
        public string IndexKeywords { get; set; }
        public string MolecularSequenceNumbers { get; set; }
        public string ChemicalsCAS { get; set; }
        public string Tradenames { get; set; }
        public string Manufacturers { get; set; }
        public string FundingDetails { get; set; }
        public string Refs { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string Editors { get; set; }
        public string Sponsors { get; set; }
        public string Publisher { get; set; }
        public string ConferenceName { get; set; }
        public string ConferenceDate { get; set; }
        public string ConferenceLocation { get; set; }
        public Nullable<int> ConferenceCode { get; set; }
        public string ISSN { get; set; }
        public string ISBN { get; set; }
        public string CODEN { get; set; }
        public string DOI { get; set; }
        public string PubMedID { get; set; }
        public string LanguageofOriginalDocument { get; set; }
        public string AbbreviatedSourceTitle { get; set; }
        public string DocumentType { get; set; }
        public string Source { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string StemmedAbstract { get; set; }
        public string AbstractWithoutQuotes { get; set; }
        public string TitleWithoutQuotes { get; set; }
        public Nullable<int> coPublicationsId { get; set; }
        public string eid { get; set; }
        public string StemmedTitle { get; set; }
    
        public virtual ICollection<link> link1 { get; set; }
    }
}
