//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wofraConnection : DbContext
    {
        public wofraConnection()
            : base("name=wofraConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<paper> paper { get; set; }
        public DbSet<link> link { get; set; }
        public DbSet<node> node { get; set; }
        public DbSet<preNode> preNode { get; set; }
        public DbSet<preLink> preLink { get; set; }
    }
}
